/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/代码Agent-核心竞争力从模型转向云端开发机': RouteRecordInfo<
      '/posts/ai/agent/代码Agent-核心竞争力从模型转向云端开发机',
      '/posts/ai/agent/%E4%BB%A3%E7%A0%81Agent-%E6%A0%B8%E5%BF%83%E7%AB%9E%E4%BA%89%E5%8A%9B%E4%BB%8E%E6%A8%A1%E5%9E%8B%E8%BD%AC%E5%90%91%E4%BA%91%E7%AB%AF%E5%BC%80%E5%8F%91%E6%9C%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/嵌入式Agent-卡住的不是代码是回路': RouteRecordInfo<
      '/posts/ai/agent/嵌入式Agent-卡住的不是代码是回路',
      '/posts/ai/agent/%E5%B5%8C%E5%85%A5%E5%BC%8FAgent-%E5%8D%A1%E4%BD%8F%E7%9A%84%E4%B8%8D%E6%98%AF%E4%BB%A3%E7%A0%81%E6%98%AF%E5%9B%9E%E8%B7%AF',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/推荐文 cua-让AI接管真实桌面的开源驱动': RouteRecordInfo<
      '/posts/ai/agent/推荐文 cua-让AI接管真实桌面的开源驱动',
      '/posts/ai/agent/%E6%8E%A8%E8%8D%90%E6%96%87%20cua-%E8%AE%A9AI%E6%8E%A5%E7%AE%A1%E7%9C%9F%E5%AE%9E%E6%A1%8C%E9%9D%A2%E7%9A%84%E5%BC%80%E6%BA%90%E9%A9%B1%E5%8A%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/给AI建方案索引-让它别重新设计做过的东西': RouteRecordInfo<
      '/posts/ai/agent/给AI建方案索引-让它别重新设计做过的东西',
      '/posts/ai/agent/%E7%BB%99AI%E5%BB%BA%E6%96%B9%E6%A1%88%E7%B4%A2%E5%BC%95-%E8%AE%A9%E5%AE%83%E5%88%AB%E9%87%8D%E6%96%B0%E8%AE%BE%E8%AE%A1%E5%81%9A%E8%BF%87%E7%9A%84%E4%B8%9C%E8%A5%BF',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/Agent 跨端开发两个月有感': RouteRecordInfo<
      '/posts/ai/agent/Agent 跨端开发两个月有感',
      '/posts/ai/agent/Agent%20%E8%B7%A8%E7%AB%AF%E5%BC%80%E5%8F%91%E4%B8%A4%E4%B8%AA%E6%9C%88%E6%9C%89%E6%84%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/Agent记忆-难的不是记住而是退场': RouteRecordInfo<
      '/posts/ai/agent/Agent记忆-难的不是记住而是退场',
      '/posts/ai/agent/Agent%E8%AE%B0%E5%BF%86-%E9%9A%BE%E7%9A%84%E4%B8%8D%E6%98%AF%E8%AE%B0%E4%BD%8F%E8%80%8C%E6%98%AF%E9%80%80%E5%9C%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/archify-让Agent画出能验证的交互架构图': RouteRecordInfo<
      '/posts/ai/agent/archify-让Agent画出能验证的交互架构图',
      '/posts/ai/agent/archify-%E8%AE%A9Agent%E7%94%BB%E5%87%BA%E8%83%BD%E9%AA%8C%E8%AF%81%E7%9A%84%E4%BA%A4%E4%BA%92%E6%9E%B6%E6%9E%84%E5%9B%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/collusion-wiki-AI们的小群聊天记录': RouteRecordInfo<
      '/posts/ai/agent/collusion-wiki-AI们的小群聊天记录',
      '/posts/ai/agent/collusion-wiki-AI%E4%BB%AC%E7%9A%84%E5%B0%8F%E7%BE%A4%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/T5AI开发板-描述效果就能出demo': RouteRecordInfo<
      '/posts/ai/agent/T5AI开发板-描述效果就能出demo',
      '/posts/ai/agent/T5AI%E5%BC%80%E5%8F%91%E6%9D%BF-%E6%8F%8F%E8%BF%B0%E6%95%88%E6%9E%9C%E5%B0%B1%E8%83%BD%E5%87%BAdemo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/WebMCP-computer-use的换代': RouteRecordInfo<
      '/posts/ai/agent/WebMCP-computer-use的换代',
      '/posts/ai/agent/WebMCP-computer-use%E7%9A%84%E6%8D%A2%E4%BB%A3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/agent/WeWorm-蠕虫工期被压到一周': RouteRecordInfo<
      '/posts/ai/agent/WeWorm-蠕虫工期被压到一周',
      '/posts/ai/agent/WeWorm-%E8%A0%95%E8%99%AB%E5%B7%A5%E6%9C%9F%E8%A2%AB%E5%8E%8B%E5%88%B0%E4%B8%80%E5%91%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/models/同一句提示词跑四次两次连物理模型都不是一类': RouteRecordInfo<
      '/posts/ai/models/同一句提示词跑四次两次连物理模型都不是一类',
      '/posts/ai/models/%E5%90%8C%E4%B8%80%E5%8F%A5%E6%8F%90%E7%A4%BA%E8%AF%8D%E8%B7%91%E5%9B%9B%E6%AC%A1%E4%B8%A4%E6%AC%A1%E8%BF%9E%E7%89%A9%E7%90%86%E6%A8%A1%E5%9E%8B%E9%83%BD%E4%B8%8D%E6%98%AF%E4%B8%80%E7%B1%BB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/models/AI破解370年密码-不是天才是耐心': RouteRecordInfo<
      '/posts/ai/models/AI破解370年密码-不是天才是耐心',
      '/posts/ai/models/AI%E7%A0%B4%E8%A7%A3370%E5%B9%B4%E5%AF%86%E7%A0%81-%E4%B8%8D%E6%98%AF%E5%A4%A9%E6%89%8D%E6%98%AF%E8%80%90%E5%BF%83',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/models/Anthropic-把插件市场的PR入口关了': RouteRecordInfo<
      '/posts/ai/models/Anthropic-把插件市场的PR入口关了',
      '/posts/ai/models/Anthropic-%E6%8A%8A%E6%8F%92%E4%BB%B6%E5%B8%82%E5%9C%BA%E7%9A%84PR%E5%85%A5%E5%8F%A3%E5%85%B3%E4%BA%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/models/DeepSeek-V4-Flash-Vision-Exp-给V4-Flash装上眼睛': RouteRecordInfo<
      '/posts/ai/models/DeepSeek-V4-Flash-Vision-Exp-给V4-Flash装上眼睛',
      '/posts/ai/models/DeepSeek-V4-Flash-Vision-Exp-%E7%BB%99V4-Flash%E8%A3%85%E4%B8%8A%E7%9C%BC%E7%9D%9B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/models/DeepSeek-V4.1-Flash-速度很快但交付未必快': RouteRecordInfo<
      '/posts/ai/models/DeepSeek-V4.1-Flash-速度很快但交付未必快',
      '/posts/ai/models/DeepSeek-V4/1-Flash-%E9%80%9F%E5%BA%A6%E5%BE%88%E5%BF%AB%E4%BD%86%E4%BA%A4%E4%BB%98%E6%9C%AA%E5%BF%85%E5%BF%AB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/models/GPT6-Astra-vs-Fable5.1-跑分归Claude编码性价比归OpenAI': RouteRecordInfo<
      '/posts/ai/models/GPT6-Astra-vs-Fable5.1-跑分归Claude编码性价比归OpenAI',
      '/posts/ai/models/GPT6-Astra-vs-Fable5/1-%E8%B7%91%E5%88%86%E5%BD%92Claude%E7%BC%96%E7%A0%81%E6%80%A7%E4%BB%B7%E6%AF%94%E5%BD%92OpenAI',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/models/Jev-把判断从生成里拆出来': RouteRecordInfo<
      '/posts/ai/models/Jev-把判断从生成里拆出来',
      '/posts/ai/models/Jev-%E6%8A%8A%E5%88%A4%E6%96%AD%E4%BB%8E%E7%94%9F%E6%88%90%E9%87%8C%E6%8B%86%E5%87%BA%E6%9D%A5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/tools/Claude-Code-一个引擎两种表现': RouteRecordInfo<
      '/posts/ai/tools/Claude-Code-一个引擎两种表现',
      '/posts/ai/tools/Claude-Code-%E4%B8%80%E4%B8%AA%E5%BC%95%E6%93%8E%E4%B8%A4%E7%A7%8D%E8%A1%A8%E7%8E%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/tools/CLAUDE.md不是配置文件是一段用户消息': RouteRecordInfo<
      '/posts/ai/tools/CLAUDE.md不是配置文件是一段用户消息',
      '/posts/ai/tools/CLAUDE/md%E4%B8%8D%E6%98%AF%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E6%98%AF%E4%B8%80%E6%AE%B5%E7%94%A8%E6%88%B7%E6%B6%88%E6%81%AF',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/tools/DeepSeek-Harness-架构实测': RouteRecordInfo<
      '/posts/ai/tools/DeepSeek-Harness-架构实测',
      '/posts/ai/tools/DeepSeek-Harness-%E6%9E%B6%E6%9E%84%E5%AE%9E%E6%B5%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/tools/DSH插件生态-清单站与周边工具': RouteRecordInfo<
      '/posts/ai/tools/DSH插件生态-清单站与周边工具',
      '/posts/ai/tools/DSH%E6%8F%92%E4%BB%B6%E7%94%9F%E6%80%81-%E6%B8%85%E5%8D%95%E7%AB%99%E4%B8%8E%E5%91%A8%E8%BE%B9%E5%B7%A5%E5%85%B7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/tools/LangChain-删掉自己的系统提示词': RouteRecordInfo<
      '/posts/ai/tools/LangChain-删掉自己的系统提示词',
      '/posts/ai/tools/LangChain-%E5%88%A0%E6%8E%89%E8%87%AA%E5%B7%B1%E7%9A%84%E7%B3%BB%E7%BB%9F%E6%8F%90%E7%A4%BA%E8%AF%8D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/tools/Ocean网关-模型选型对比': RouteRecordInfo<
      '/posts/ai/tools/Ocean网关-模型选型对比',
      '/posts/ai/tools/Ocean%E7%BD%91%E5%85%B3-%E6%A8%A1%E5%9E%8B%E9%80%89%E5%9E%8B%E5%AF%B9%E6%AF%94',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/tools/omp与opencode对比-同一个模型两份答案': RouteRecordInfo<
      '/posts/ai/tools/omp与opencode对比-同一个模型两份答案',
      '/posts/ai/tools/omp%E4%B8%8Eopencode%E5%AF%B9%E6%AF%94-%E5%90%8C%E4%B8%80%E4%B8%AA%E6%A8%A1%E5%9E%8B%E4%B8%A4%E4%BB%BD%E7%AD%94%E6%A1%88',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/tools/OpenCodeReview-能确定性解决的就不劳烦AI': RouteRecordInfo<
      '/posts/ai/tools/OpenCodeReview-能确定性解决的就不劳烦AI',
      '/posts/ai/tools/OpenCodeReview-%E8%83%BD%E7%A1%AE%E5%AE%9A%E6%80%A7%E8%A7%A3%E5%86%B3%E7%9A%84%E5%B0%B1%E4%B8%8D%E5%8A%B3%E7%83%A6AI',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/tools/rtk-一次mvn编译就能吃掉32万token': RouteRecordInfo<
      '/posts/ai/tools/rtk-一次mvn编译就能吃掉32万token',
      '/posts/ai/tools/rtk-%E4%B8%80%E6%AC%A1mvn%E7%BC%96%E8%AF%91%E5%B0%B1%E8%83%BD%E5%90%83%E6%8E%8932%E4%B8%87token',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai/tools/Superpowers-砍掉了自己一半的token': RouteRecordInfo<
      '/posts/ai/tools/Superpowers-砍掉了自己一半的token',
      '/posts/ai/tools/Superpowers-%E7%A0%8D%E6%8E%89%E4%BA%86%E8%87%AA%E5%B7%B1%E4%B8%80%E5%8D%8A%E7%9A%84token',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/course/数据处理的一般模式': RouteRecordInfo<
      '/posts/big-data/course/数据处理的一般模式',
      '/posts/big-data/course/%E6%95%B0%E6%8D%AE%E5%A4%84%E7%90%86%E7%9A%84%E4%B8%80%E8%88%AC%E6%A8%A1%E5%BC%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/course/流式计算模型': RouteRecordInfo<
      '/posts/big-data/course/流式计算模型',
      '/posts/big-data/course/%E6%B5%81%E5%BC%8F%E8%AE%A1%E7%AE%97%E6%A8%A1%E5%9E%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/course/考试': RouteRecordInfo<
      '/posts/big-data/course/考试',
      '/posts/big-data/course/%E8%80%83%E8%AF%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/course/Spark RDD算子': RouteRecordInfo<
      '/posts/big-data/course/Spark RDD算子',
      '/posts/big-data/course/Spark%20RDD%E7%AE%97%E5%AD%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/course/Spark SQL': RouteRecordInfo<
      '/posts/big-data/course/Spark SQL',
      '/posts/big-data/course/Spark%20SQL',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/course/Spark工作原理': RouteRecordInfo<
      '/posts/big-data/course/Spark工作原理',
      '/posts/big-data/course/Spark%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/course/Spark案例分析': RouteRecordInfo<
      '/posts/big-data/course/Spark案例分析',
      '/posts/big-data/course/Spark%E6%A1%88%E4%BE%8B%E5%88%86%E6%9E%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/flink/Flink编程 DataStreamAPI': RouteRecordInfo<
      '/posts/big-data/labs/flink/Flink编程 DataStreamAPI',
      '/posts/big-data/labs/flink/Flink%E7%BC%96%E7%A8%8B%20DataStreamAPI',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/flink/Flink编程 Table API&SQL': RouteRecordInfo<
      '/posts/big-data/labs/flink/Flink编程 Table API&SQL',
      '/posts/big-data/labs/flink/Flink%E7%BC%96%E7%A8%8B%20Table%20API&SQL',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/flink/Flink部署': RouteRecordInfo<
      '/posts/big-data/labs/flink/Flink部署',
      '/posts/big-data/labs/flink/Flink%E9%83%A8%E7%BD%B2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/hbase/HBase伪分布式部署': RouteRecordInfo<
      '/posts/big-data/labs/hbase/HBase伪分布式部署',
      '/posts/big-data/labs/hbase/HBase%E4%BC%AA%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/hbase/HBaseShell接口操作': RouteRecordInfo<
      '/posts/big-data/labs/hbase/HBaseShell接口操作',
      '/posts/big-data/labs/hbase/HBaseShell%E6%8E%A5%E5%8F%A3%E6%93%8D%E4%BD%9C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/hbase/HBaseWebUI管理': RouteRecordInfo<
      '/posts/big-data/labs/hbase/HBaseWebUI管理',
      '/posts/big-data/labs/hbase/HBaseWebUI%E7%AE%A1%E7%90%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/hbase/JavaAPI命名空间操作': RouteRecordInfo<
      '/posts/big-data/labs/hbase/JavaAPI命名空间操作',
      '/posts/big-data/labs/hbase/JavaAPI%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4%E6%93%8D%E4%BD%9C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/hbase/JavaAPI表操作': RouteRecordInfo<
      '/posts/big-data/labs/hbase/JavaAPI表操作',
      '/posts/big-data/labs/hbase/JavaAPI%E8%A1%A8%E6%93%8D%E4%BD%9C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/hive/使用HQL窗口函数': RouteRecordInfo<
      '/posts/big-data/labs/hive/使用HQL窗口函数',
      '/posts/big-data/labs/hive/%E4%BD%BF%E7%94%A8HQL%E7%AA%97%E5%8F%A3%E5%87%BD%E6%95%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/hive/数据库和数据表定义': RouteRecordInfo<
      '/posts/big-data/labs/hive/数据库和数据表定义',
      '/posts/big-data/labs/hive/%E6%95%B0%E6%8D%AE%E5%BA%93%E5%92%8C%E6%95%B0%E6%8D%AE%E8%A1%A8%E5%AE%9A%E4%B9%89',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/hive/Hive的安装部署': RouteRecordInfo<
      '/posts/big-data/labs/hive/Hive的安装部署',
      '/posts/big-data/labs/hive/Hive%E7%9A%84%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/hive/HiveCLI命令行接口使用': RouteRecordInfo<
      '/posts/big-data/labs/hive/HiveCLI命令行接口使用',
      '/posts/big-data/labs/hive/HiveCLI%E5%91%BD%E4%BB%A4%E8%A1%8C%E6%8E%A5%E5%8F%A3%E4%BD%BF%E7%94%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/hive/HQL多表连接查询': RouteRecordInfo<
      '/posts/big-data/labs/hive/HQL多表连接查询',
      '/posts/big-data/labs/hive/HQL%E5%A4%9A%E8%A1%A8%E8%BF%9E%E6%8E%A5%E6%9F%A5%E8%AF%A2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/intro/数据和处理的抽象': RouteRecordInfo<
      '/posts/big-data/labs/intro/数据和处理的抽象',
      '/posts/big-data/labs/intro/%E6%95%B0%E6%8D%AE%E5%92%8C%E5%A4%84%E7%90%86%E7%9A%84%E6%8A%BD%E8%B1%A1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/spark/实验七 Spark SQL：普通样例类编程': RouteRecordInfo<
      '/posts/big-data/labs/spark/实验七 Spark SQL：普通样例类编程',
      '/posts/big-data/labs/spark/%E5%AE%9E%E9%AA%8C%E4%B8%83%20Spark%20SQL%EF%BC%9A%E6%99%AE%E9%80%9A%E6%A0%B7%E4%BE%8B%E7%B1%BB%E7%BC%96%E7%A8%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/spark/实验八 Spark SQL：领域API编程': RouteRecordInfo<
      '/posts/big-data/labs/spark/实验八 Spark SQL：领域API编程',
      '/posts/big-data/labs/spark/%E5%AE%9E%E9%AA%8C%E5%85%AB%20Spark%20SQL%EF%BC%9A%E9%A2%86%E5%9F%9FAPI%E7%BC%96%E7%A8%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/spark/实验六 Spark SQL：命令方式': RouteRecordInfo<
      '/posts/big-data/labs/spark/实验六 Spark SQL：命令方式',
      '/posts/big-data/labs/spark/%E5%AE%9E%E9%AA%8C%E5%85%AD%20Spark%20SQL%EF%BC%9A%E5%91%BD%E4%BB%A4%E6%96%B9%E5%BC%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/spark/Spark安装部署：On Yarn模式': RouteRecordInfo<
      '/posts/big-data/labs/spark/Spark安装部署：On Yarn模式',
      '/posts/big-data/labs/spark/Spark%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2%EF%BC%9AOn%20Yarn%E6%A8%A1%E5%BC%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/spark/Spark安装部署：Standalone模式': RouteRecordInfo<
      '/posts/big-data/labs/spark/Spark安装部署：Standalone模式',
      '/posts/big-data/labs/spark/Spark%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2%EF%BC%9AStandalone%E6%A8%A1%E5%BC%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/spark/SparkRDD': RouteRecordInfo<
      '/posts/big-data/labs/spark/SparkRDD',
      '/posts/big-data/labs/spark/SparkRDD',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/warehouse/实时仓库搭建': RouteRecordInfo<
      '/posts/big-data/labs/warehouse/实时仓库搭建',
      '/posts/big-data/labs/warehouse/%E5%AE%9E%E6%97%B6%E4%BB%93%E5%BA%93%E6%90%AD%E5%BB%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/warehouse/数据同步': RouteRecordInfo<
      '/posts/big-data/labs/warehouse/数据同步',
      '/posts/big-data/labs/warehouse/%E6%95%B0%E6%8D%AE%E5%90%8C%E6%AD%A5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/warehouse/数据采集': RouteRecordInfo<
      '/posts/big-data/labs/warehouse/数据采集',
      '/posts/big-data/labs/warehouse/%E6%95%B0%E6%8D%AE%E9%87%87%E9%9B%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/big-data/labs/warehouse/离线仓库搭建': RouteRecordInfo<
      '/posts/big-data/labs/warehouse/离线仓库搭建',
      '/posts/big-data/labs/warehouse/%E7%A6%BB%E7%BA%BF%E4%BB%93%E5%BA%93%E6%90%AD%E5%BB%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cloud/云计算与分布式-存储技术': RouteRecordInfo<
      '/posts/cloud/云计算与分布式-存储技术',
      '/posts/cloud/%E4%BA%91%E8%AE%A1%E7%AE%97%E4%B8%8E%E5%88%86%E5%B8%83%E5%BC%8F-%E5%AD%98%E5%82%A8%E6%8A%80%E6%9C%AF',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cloud/flume的安装与使用': RouteRecordInfo<
      '/posts/cloud/flume的安装与使用',
      '/posts/cloud/flume%E7%9A%84%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cloud/Hadoop安装与配置': RouteRecordInfo<
      '/posts/cloud/Hadoop安装与配置',
      '/posts/cloud/Hadoop%E5%AE%89%E8%A3%85%E4%B8%8E%E9%85%8D%E7%BD%AE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cloud/HDFS实验报告': RouteRecordInfo<
      '/posts/cloud/HDFS实验报告',
      '/posts/cloud/HDFS%E5%AE%9E%E9%AA%8C%E6%8A%A5%E5%91%8A',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cloud/Linux下Kafka的安装与配置': RouteRecordInfo<
      '/posts/cloud/Linux下Kafka的安装与配置',
      '/posts/cloud/Linux%E4%B8%8BKafka%E7%9A%84%E5%AE%89%E8%A3%85%E4%B8%8E%E9%85%8D%E7%BD%AE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cloud/MapReduce': RouteRecordInfo<
      '/posts/cloud/MapReduce',
      '/posts/cloud/MapReduce',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cloud/YARN实践': RouteRecordInfo<
      '/posts/cloud/YARN实践',
      '/posts/cloud/YARN%E5%AE%9E%E8%B7%B5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cloud/Zookeeper': RouteRecordInfo<
      '/posts/cloud/Zookeeper',
      '/posts/cloud/Zookeeper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cs-fundamentals/图解HTTP': RouteRecordInfo<
      '/posts/cs-fundamentals/图解HTTP',
      '/posts/cs-fundamentals/%E5%9B%BE%E8%A7%A3HTTP',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cs-fundamentals/绪论': RouteRecordInfo<
      '/posts/cs-fundamentals/绪论',
      '/posts/cs-fundamentals/%E7%BB%AA%E8%AE%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cs-fundamentals/Java基础': RouteRecordInfo<
      '/posts/cs-fundamentals/Java基础',
      '/posts/cs-fundamentals/Java%E5%9F%BA%E7%A1%80',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/data-analysis/线性回归实践': RouteRecordInfo<
      '/posts/data-analysis/线性回归实践',
      '/posts/data-analysis/%E7%BA%BF%E6%80%A7%E5%9B%9E%E5%BD%92%E5%AE%9E%E8%B7%B5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/data-analysis/黑猫数据分析': RouteRecordInfo<
      '/posts/data-analysis/黑猫数据分析',
      '/posts/data-analysis/%E9%BB%91%E7%8C%AB%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/database/磁盘管理实验作业 1.1': RouteRecordInfo<
      '/posts/database/磁盘管理实验作业 1.1',
      '/posts/database/%E7%A3%81%E7%9B%98%E7%AE%A1%E7%90%86%E5%AE%9E%E9%AA%8C%E4%BD%9C%E4%B8%9A%201/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/database/老师任务之复杂的多表查询SQL': RouteRecordInfo<
      '/posts/database/老师任务之复杂的多表查询SQL',
      '/posts/database/%E8%80%81%E5%B8%88%E4%BB%BB%E5%8A%A1%E4%B9%8B%E5%A4%8D%E6%9D%82%E7%9A%84%E5%A4%9A%E8%A1%A8%E6%9F%A5%E8%AF%A2SQL',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/dev-practice/小技巧才是复利-从一篇HN热帖到我踩过的坑': RouteRecordInfo<
      '/posts/dev-practice/小技巧才是复利-从一篇HN热帖到我踩过的坑',
      '/posts/dev-practice/%E5%B0%8F%E6%8A%80%E5%B7%A7%E6%89%8D%E6%98%AF%E5%A4%8D%E5%88%A9-%E4%BB%8E%E4%B8%80%E7%AF%87HN%E7%83%AD%E5%B8%96%E5%88%B0%E6%88%91%E8%B8%A9%E8%BF%87%E7%9A%84%E5%9D%91',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/dev-practice/登录鉴权-Cookie-Session-JWT-SSO一次讲清': RouteRecordInfo<
      '/posts/dev-practice/登录鉴权-Cookie-Session-JWT-SSO一次讲清',
      '/posts/dev-practice/%E7%99%BB%E5%BD%95%E9%89%B4%E6%9D%83-Cookie-Session-JWT-SSO%E4%B8%80%E6%AC%A1%E8%AE%B2%E6%B8%85',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/dev-practice/Shopify-弃RN回原生-不是性能是agent': RouteRecordInfo<
      '/posts/dev-practice/Shopify-弃RN回原生-不是性能是agent',
      '/posts/dev-practice/Shopify-%E5%BC%83RN%E5%9B%9E%E5%8E%9F%E7%94%9F-%E4%B8%8D%E6%98%AF%E6%80%A7%E8%83%BD%E6%98%AFagent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/devtools/docker实验': RouteRecordInfo<
      '/posts/devtools/docker实验',
      '/posts/devtools/docker%E5%AE%9E%E9%AA%8C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/devtools/Easydict-技术向推文': RouteRecordInfo<
      '/posts/devtools/Easydict-技术向推文',
      '/posts/devtools/Easydict-%E6%8A%80%E6%9C%AF%E5%90%91%E6%8E%A8%E6%96%87',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/devtools/fnm-Node版本管理工具推荐': RouteRecordInfo<
      '/posts/devtools/fnm-Node版本管理工具推荐',
      '/posts/devtools/fnm-Node%E7%89%88%E6%9C%AC%E7%AE%A1%E7%90%86%E5%B7%A5%E5%85%B7%E6%8E%A8%E8%8D%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/devtools/Loki日志排障指南': RouteRecordInfo<
      '/posts/devtools/Loki日志排障指南',
      '/posts/devtools/Loki%E6%97%A5%E5%BF%97%E6%8E%92%E9%9A%9C%E6%8C%87%E5%8D%97',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/devtools/mise-开发环境统一工具推荐': RouteRecordInfo<
      '/posts/devtools/mise-开发环境统一工具推荐',
      '/posts/devtools/mise-%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E7%BB%9F%E4%B8%80%E5%B7%A5%E5%85%B7%E6%8E%A8%E8%8D%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/devtools/ubuntu常用命令记录': RouteRecordInfo<
      '/posts/devtools/ubuntu常用命令记录',
      '/posts/devtools/ubuntu%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4%E8%AE%B0%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/devtools/yazi-终端文件管理器推荐': RouteRecordInfo<
      '/posts/devtools/yazi-终端文件管理器推荐',
      '/posts/devtools/yazi-%E7%BB%88%E7%AB%AF%E6%96%87%E4%BB%B6%E7%AE%A1%E7%90%86%E5%99%A8%E6%8E%A8%E8%8D%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.1_29226f0b53e1f0fd67df281a69ab8f5e/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-rc.15_@babel+p_a6909858ae4298a3374f89e4d58e5156/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.1_29226f0b53e1f0fd67df281a69ab8f5e/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.1_29226f0b53e1f0fd67df281a69ab8f5e/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/ai/agent/代码Agent-核心竞争力从模型转向云端开发机.md': {
      routes:
        | '/posts/ai/agent/代码Agent-核心竞争力从模型转向云端开发机'
      views:
        | never
    }
    'pages/posts/ai/agent/嵌入式Agent-卡住的不是代码是回路.md': {
      routes:
        | '/posts/ai/agent/嵌入式Agent-卡住的不是代码是回路'
      views:
        | never
    }
    'pages/posts/ai/agent/推荐文 cua-让AI接管真实桌面的开源驱动.md': {
      routes:
        | '/posts/ai/agent/推荐文 cua-让AI接管真实桌面的开源驱动'
      views:
        | never
    }
    'pages/posts/ai/agent/给AI建方案索引-让它别重新设计做过的东西.md': {
      routes:
        | '/posts/ai/agent/给AI建方案索引-让它别重新设计做过的东西'
      views:
        | never
    }
    'pages/posts/ai/agent/Agent 跨端开发两个月有感.md': {
      routes:
        | '/posts/ai/agent/Agent 跨端开发两个月有感'
      views:
        | never
    }
    'pages/posts/ai/agent/Agent记忆-难的不是记住而是退场.md': {
      routes:
        | '/posts/ai/agent/Agent记忆-难的不是记住而是退场'
      views:
        | never
    }
    'pages/posts/ai/agent/archify-让Agent画出能验证的交互架构图.md': {
      routes:
        | '/posts/ai/agent/archify-让Agent画出能验证的交互架构图'
      views:
        | never
    }
    'pages/posts/ai/agent/collusion-wiki-AI们的小群聊天记录.md': {
      routes:
        | '/posts/ai/agent/collusion-wiki-AI们的小群聊天记录'
      views:
        | never
    }
    'pages/posts/ai/agent/T5AI开发板-描述效果就能出demo.md': {
      routes:
        | '/posts/ai/agent/T5AI开发板-描述效果就能出demo'
      views:
        | never
    }
    'pages/posts/ai/agent/WebMCP-computer-use的换代.md': {
      routes:
        | '/posts/ai/agent/WebMCP-computer-use的换代'
      views:
        | never
    }
    'pages/posts/ai/agent/WeWorm-蠕虫工期被压到一周.md': {
      routes:
        | '/posts/ai/agent/WeWorm-蠕虫工期被压到一周'
      views:
        | never
    }
    'pages/posts/ai/models/同一句提示词跑四次两次连物理模型都不是一类.md': {
      routes:
        | '/posts/ai/models/同一句提示词跑四次两次连物理模型都不是一类'
      views:
        | never
    }
    'pages/posts/ai/models/AI破解370年密码-不是天才是耐心.md': {
      routes:
        | '/posts/ai/models/AI破解370年密码-不是天才是耐心'
      views:
        | never
    }
    'pages/posts/ai/models/Anthropic-把插件市场的PR入口关了.md': {
      routes:
        | '/posts/ai/models/Anthropic-把插件市场的PR入口关了'
      views:
        | never
    }
    'pages/posts/ai/models/DeepSeek-V4-Flash-Vision-Exp-给V4-Flash装上眼睛.md': {
      routes:
        | '/posts/ai/models/DeepSeek-V4-Flash-Vision-Exp-给V4-Flash装上眼睛'
      views:
        | never
    }
    'pages/posts/ai/models/DeepSeek-V4.1-Flash-速度很快但交付未必快.md': {
      routes:
        | '/posts/ai/models/DeepSeek-V4.1-Flash-速度很快但交付未必快'
      views:
        | never
    }
    'pages/posts/ai/models/GPT6-Astra-vs-Fable5.1-跑分归Claude编码性价比归OpenAI.md': {
      routes:
        | '/posts/ai/models/GPT6-Astra-vs-Fable5.1-跑分归Claude编码性价比归OpenAI'
      views:
        | never
    }
    'pages/posts/ai/models/Jev-把判断从生成里拆出来.md': {
      routes:
        | '/posts/ai/models/Jev-把判断从生成里拆出来'
      views:
        | never
    }
    'pages/posts/ai/tools/Claude-Code-一个引擎两种表现.md': {
      routes:
        | '/posts/ai/tools/Claude-Code-一个引擎两种表现'
      views:
        | never
    }
    'pages/posts/ai/tools/CLAUDE.md不是配置文件是一段用户消息.md': {
      routes:
        | '/posts/ai/tools/CLAUDE.md不是配置文件是一段用户消息'
      views:
        | never
    }
    'pages/posts/ai/tools/DeepSeek-Harness-架构实测.md': {
      routes:
        | '/posts/ai/tools/DeepSeek-Harness-架构实测'
      views:
        | never
    }
    'pages/posts/ai/tools/DSH插件生态-清单站与周边工具.md': {
      routes:
        | '/posts/ai/tools/DSH插件生态-清单站与周边工具'
      views:
        | never
    }
    'pages/posts/ai/tools/LangChain-删掉自己的系统提示词.md': {
      routes:
        | '/posts/ai/tools/LangChain-删掉自己的系统提示词'
      views:
        | never
    }
    'pages/posts/ai/tools/Ocean网关-模型选型对比.md': {
      routes:
        | '/posts/ai/tools/Ocean网关-模型选型对比'
      views:
        | never
    }
    'pages/posts/ai/tools/omp与opencode对比-同一个模型两份答案.md': {
      routes:
        | '/posts/ai/tools/omp与opencode对比-同一个模型两份答案'
      views:
        | never
    }
    'pages/posts/ai/tools/OpenCodeReview-能确定性解决的就不劳烦AI.md': {
      routes:
        | '/posts/ai/tools/OpenCodeReview-能确定性解决的就不劳烦AI'
      views:
        | never
    }
    'pages/posts/ai/tools/rtk-一次mvn编译就能吃掉32万token.md': {
      routes:
        | '/posts/ai/tools/rtk-一次mvn编译就能吃掉32万token'
      views:
        | never
    }
    'pages/posts/ai/tools/Superpowers-砍掉了自己一半的token.md': {
      routes:
        | '/posts/ai/tools/Superpowers-砍掉了自己一半的token'
      views:
        | never
    }
    'pages/posts/big-data/course/数据处理的一般模式.md': {
      routes:
        | '/posts/big-data/course/数据处理的一般模式'
      views:
        | never
    }
    'pages/posts/big-data/course/流式计算模型.md': {
      routes:
        | '/posts/big-data/course/流式计算模型'
      views:
        | never
    }
    'pages/posts/big-data/course/考试.md': {
      routes:
        | '/posts/big-data/course/考试'
      views:
        | never
    }
    'pages/posts/big-data/course/Spark RDD算子.md': {
      routes:
        | '/posts/big-data/course/Spark RDD算子'
      views:
        | never
    }
    'pages/posts/big-data/course/Spark SQL.md': {
      routes:
        | '/posts/big-data/course/Spark SQL'
      views:
        | never
    }
    'pages/posts/big-data/course/Spark工作原理.md': {
      routes:
        | '/posts/big-data/course/Spark工作原理'
      views:
        | never
    }
    'pages/posts/big-data/course/Spark案例分析.md': {
      routes:
        | '/posts/big-data/course/Spark案例分析'
      views:
        | never
    }
    'pages/posts/big-data/labs/flink/Flink编程 DataStreamAPI.md': {
      routes:
        | '/posts/big-data/labs/flink/Flink编程 DataStreamAPI'
      views:
        | never
    }
    'pages/posts/big-data/labs/flink/Flink编程 Table API&SQL.md': {
      routes:
        | '/posts/big-data/labs/flink/Flink编程 Table API&SQL'
      views:
        | never
    }
    'pages/posts/big-data/labs/flink/Flink部署.md': {
      routes:
        | '/posts/big-data/labs/flink/Flink部署'
      views:
        | never
    }
    'pages/posts/big-data/labs/hbase/HBase伪分布式部署.md': {
      routes:
        | '/posts/big-data/labs/hbase/HBase伪分布式部署'
      views:
        | never
    }
    'pages/posts/big-data/labs/hbase/HBaseShell接口操作.md': {
      routes:
        | '/posts/big-data/labs/hbase/HBaseShell接口操作'
      views:
        | never
    }
    'pages/posts/big-data/labs/hbase/HBaseWebUI管理.md': {
      routes:
        | '/posts/big-data/labs/hbase/HBaseWebUI管理'
      views:
        | never
    }
    'pages/posts/big-data/labs/hbase/JavaAPI命名空间操作.md': {
      routes:
        | '/posts/big-data/labs/hbase/JavaAPI命名空间操作'
      views:
        | never
    }
    'pages/posts/big-data/labs/hbase/JavaAPI表操作.md': {
      routes:
        | '/posts/big-data/labs/hbase/JavaAPI表操作'
      views:
        | never
    }
    'pages/posts/big-data/labs/hive/使用HQL窗口函数.md': {
      routes:
        | '/posts/big-data/labs/hive/使用HQL窗口函数'
      views:
        | never
    }
    'pages/posts/big-data/labs/hive/数据库和数据表定义.md': {
      routes:
        | '/posts/big-data/labs/hive/数据库和数据表定义'
      views:
        | never
    }
    'pages/posts/big-data/labs/hive/Hive的安装部署.md': {
      routes:
        | '/posts/big-data/labs/hive/Hive的安装部署'
      views:
        | never
    }
    'pages/posts/big-data/labs/hive/HiveCLI命令行接口使用.md': {
      routes:
        | '/posts/big-data/labs/hive/HiveCLI命令行接口使用'
      views:
        | never
    }
    'pages/posts/big-data/labs/hive/HQL多表连接查询.md': {
      routes:
        | '/posts/big-data/labs/hive/HQL多表连接查询'
      views:
        | never
    }
    'pages/posts/big-data/labs/intro/数据和处理的抽象.md': {
      routes:
        | '/posts/big-data/labs/intro/数据和处理的抽象'
      views:
        | never
    }
    'pages/posts/big-data/labs/spark/实验七 Spark SQL：普通样例类编程.md': {
      routes:
        | '/posts/big-data/labs/spark/实验七 Spark SQL：普通样例类编程'
      views:
        | never
    }
    'pages/posts/big-data/labs/spark/实验八 Spark SQL：领域API编程.md': {
      routes:
        | '/posts/big-data/labs/spark/实验八 Spark SQL：领域API编程'
      views:
        | never
    }
    'pages/posts/big-data/labs/spark/实验六 Spark SQL：命令方式.md': {
      routes:
        | '/posts/big-data/labs/spark/实验六 Spark SQL：命令方式'
      views:
        | never
    }
    'pages/posts/big-data/labs/spark/Spark安装部署：On Yarn模式.md': {
      routes:
        | '/posts/big-data/labs/spark/Spark安装部署：On Yarn模式'
      views:
        | never
    }
    'pages/posts/big-data/labs/spark/Spark安装部署：Standalone模式.md': {
      routes:
        | '/posts/big-data/labs/spark/Spark安装部署：Standalone模式'
      views:
        | never
    }
    'pages/posts/big-data/labs/spark/SparkRDD.md': {
      routes:
        | '/posts/big-data/labs/spark/SparkRDD'
      views:
        | never
    }
    'pages/posts/big-data/labs/warehouse/实时仓库搭建.md': {
      routes:
        | '/posts/big-data/labs/warehouse/实时仓库搭建'
      views:
        | never
    }
    'pages/posts/big-data/labs/warehouse/数据同步.md': {
      routes:
        | '/posts/big-data/labs/warehouse/数据同步'
      views:
        | never
    }
    'pages/posts/big-data/labs/warehouse/数据采集.md': {
      routes:
        | '/posts/big-data/labs/warehouse/数据采集'
      views:
        | never
    }
    'pages/posts/big-data/labs/warehouse/离线仓库搭建.md': {
      routes:
        | '/posts/big-data/labs/warehouse/离线仓库搭建'
      views:
        | never
    }
    'pages/posts/cloud/云计算与分布式-存储技术.md': {
      routes:
        | '/posts/cloud/云计算与分布式-存储技术'
      views:
        | never
    }
    'pages/posts/cloud/flume的安装与使用.md': {
      routes:
        | '/posts/cloud/flume的安装与使用'
      views:
        | never
    }
    'pages/posts/cloud/Hadoop安装与配置.md': {
      routes:
        | '/posts/cloud/Hadoop安装与配置'
      views:
        | never
    }
    'pages/posts/cloud/HDFS实验报告.md': {
      routes:
        | '/posts/cloud/HDFS实验报告'
      views:
        | never
    }
    'pages/posts/cloud/Linux下Kafka的安装与配置.md': {
      routes:
        | '/posts/cloud/Linux下Kafka的安装与配置'
      views:
        | never
    }
    'pages/posts/cloud/MapReduce.md': {
      routes:
        | '/posts/cloud/MapReduce'
      views:
        | never
    }
    'pages/posts/cloud/YARN实践.md': {
      routes:
        | '/posts/cloud/YARN实践'
      views:
        | never
    }
    'pages/posts/cloud/Zookeeper.md': {
      routes:
        | '/posts/cloud/Zookeeper'
      views:
        | never
    }
    'pages/posts/cs-fundamentals/图解HTTP.md': {
      routes:
        | '/posts/cs-fundamentals/图解HTTP'
      views:
        | never
    }
    'pages/posts/cs-fundamentals/绪论.md': {
      routes:
        | '/posts/cs-fundamentals/绪论'
      views:
        | never
    }
    'pages/posts/cs-fundamentals/Java基础.md': {
      routes:
        | '/posts/cs-fundamentals/Java基础'
      views:
        | never
    }
    'pages/posts/data-analysis/线性回归实践.md': {
      routes:
        | '/posts/data-analysis/线性回归实践'
      views:
        | never
    }
    'pages/posts/data-analysis/黑猫数据分析.md': {
      routes:
        | '/posts/data-analysis/黑猫数据分析'
      views:
        | never
    }
    'pages/posts/database/磁盘管理实验作业 1.1.md': {
      routes:
        | '/posts/database/磁盘管理实验作业 1.1'
      views:
        | never
    }
    'pages/posts/database/老师任务之复杂的多表查询SQL.md': {
      routes:
        | '/posts/database/老师任务之复杂的多表查询SQL'
      views:
        | never
    }
    'pages/posts/dev-practice/小技巧才是复利-从一篇HN热帖到我踩过的坑.md': {
      routes:
        | '/posts/dev-practice/小技巧才是复利-从一篇HN热帖到我踩过的坑'
      views:
        | never
    }
    'pages/posts/dev-practice/登录鉴权-Cookie-Session-JWT-SSO一次讲清.md': {
      routes:
        | '/posts/dev-practice/登录鉴权-Cookie-Session-JWT-SSO一次讲清'
      views:
        | never
    }
    'pages/posts/dev-practice/Shopify-弃RN回原生-不是性能是agent.md': {
      routes:
        | '/posts/dev-practice/Shopify-弃RN回原生-不是性能是agent'
      views:
        | never
    }
    'pages/posts/devtools/docker实验.md': {
      routes:
        | '/posts/devtools/docker实验'
      views:
        | never
    }
    'pages/posts/devtools/Easydict-技术向推文.md': {
      routes:
        | '/posts/devtools/Easydict-技术向推文'
      views:
        | never
    }
    'pages/posts/devtools/fnm-Node版本管理工具推荐.md': {
      routes:
        | '/posts/devtools/fnm-Node版本管理工具推荐'
      views:
        | never
    }
    'pages/posts/devtools/Loki日志排障指南.md': {
      routes:
        | '/posts/devtools/Loki日志排障指南'
      views:
        | never
    }
    'pages/posts/devtools/mise-开发环境统一工具推荐.md': {
      routes:
        | '/posts/devtools/mise-开发环境统一工具推荐'
      views:
        | never
    }
    'pages/posts/devtools/ubuntu常用命令记录.md': {
      routes:
        | '/posts/devtools/ubuntu常用命令记录'
      views:
        | never
    }
    'pages/posts/devtools/yazi-终端文件管理器推荐.md': {
      routes:
        | '/posts/devtools/yazi-终端文件管理器推荐'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
