/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/黑猫数据分析': RouteRecordInfo<'/posts/黑猫数据分析', '/posts/黑猫数据分析', Record<never, never>, Record<never, never>>,
    '/posts/老师任务之复杂的多表查询SQL': RouteRecordInfo<'/posts/老师任务之复杂的多表查询SQL', '/posts/老师任务之复杂的多表查询SQL', Record<never, never>, Record<never, never>>,
    '/posts/图解HTTP': RouteRecordInfo<'/posts/图解HTTP', '/posts/图解HTTP', Record<never, never>, Record<never, never>>,
    '/posts/云计算与分布式-存储技术': RouteRecordInfo<'/posts/云计算与分布式-存储技术', '/posts/云计算与分布式-存储技术', Record<never, never>, Record<never, never>>,
    '/posts/docker实验': RouteRecordInfo<'/posts/docker实验', '/posts/docker实验', Record<never, never>, Record<never, never>>,
    '/posts/flume的安装与使用': RouteRecordInfo<'/posts/flume的安装与使用', '/posts/flume的安装与使用', Record<never, never>, Record<never, never>>,
    '/posts/Hadoop安装与配置': RouteRecordInfo<'/posts/Hadoop安装与配置', '/posts/Hadoop安装与配置', Record<never, never>, Record<never, never>>,
    '/posts/HDFS实验报告': RouteRecordInfo<'/posts/HDFS实验报告', '/posts/HDFS实验报告', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Linux下Kafka的安装与配置': RouteRecordInfo<'/posts/Linux下Kafka的安装与配置', '/posts/Linux下Kafka的安装与配置', Record<never, never>, Record<never, never>>,
    '/posts/MapReduce': RouteRecordInfo<'/posts/MapReduce', '/posts/MapReduce', Record<never, never>, Record<never, never>>,
    '/posts/ubuntu常用命令记录': RouteRecordInfo<'/posts/ubuntu常用命令记录', '/posts/ubuntu常用命令记录', Record<never, never>, Record<never, never>>,
    '/posts/YARN实践': RouteRecordInfo<'/posts/YARN实践', '/posts/YARN实践', Record<never, never>, Record<never, never>>,
    '/posts/Zookeeper': RouteRecordInfo<'/posts/Zookeeper', '/posts/Zookeeper', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
